version: '3'
services:
  redis-server:
    image: redis
  postgres: 
    image: postgres
    ports:
      - "35432:5432"
    volumes:
      - /postgres-data:/var/lib/postgresql/data  
    environment:
      POSTGRES_PASSWORD: pass
  node-app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis-server
    volumes:
      - ./:/usr/src/app  
    command: nodemon bin/www