version: '3'
services:
  redis-server:
    image: redis
  node-app:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis-server
    volumes:
      - ./:/usr/src/app
    command: nodemon bin/www
